# Generated by Django 5.2 on 2025-04-22 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_options_alter_keyword_options_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='api_article_author__66a63b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='api_article_status_1f2409_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['type'], name='api_article_type_0ea085_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='api_article_created_4c8c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article'], name='api_comment_article_34d342_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='api_comment_author__b4741e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='api_comment_created_db28e1_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['name'], name='api_keyword_name_36ab15_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['created_at'], name='api_keyword_created_7e90ca_idx'),
        ),
    ]
